apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres

spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:15
          envFrom:
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 5432 
          resources: # Resource limits and requests for resource management
            requests:
              memory: "256Mi" # 0.25 Gi
              cpu: "250m" # 0.25 core
            limits:
              memory: "512Mi" # 0.5 Gi
              cpu: "500m" # 0.5 core