---
- name: apply kubernetes deployments 
  hosts: local
  #become: yes
  #become_user: ahmed
  tasks:
    - name: test minikube run
      become: yes
      become_user: ahmed
      shell: |
        minikube kubectl -- get pods

    - name: Generate deployment.yaml using envsubst
      shell: |
        set -a
        source .env
        set +a
        envsubst < ../kubernates/deployment-template.yaml > ../kubernates/deployment.yaml
      args:
        executable: /bin/bash

    - name: create secret from .env file
      become: yes
      become_user: ahmed
      shell: |
        minikube kubectl -- create secret generic my-secret --from-env-file=../.env

    - name: create deployment for postgress db
      become: yes
      become_user: ahmed
      shell: |
        minikube kubectl -- apply -f ../kubernates/db-deployment.yaml

    - name: Show user name
      debug:
        msg: "App is {{ user_name }}"

    - name: create secret for docker hub registry
      become: yes
      become_user: ahmed
      shell: |
        minikube kubectl -- create secret docker-registry my-dockerhub-secret --docker-username={{ user_name }} --docker-password={{ pw }} --docker-email=hj.ahmed.hosny@gmail.com

    - name: create deployment for flask app
      become: yes
      become_user: ahmed
      shell: |
        minikube kubectl -- apply -f ../kubernates/deployment.yaml


