- name: Copy test file to remote EC2
  hosts: ec2
  become: yes
  tasks:
    - name: Copy project to remote server
      copy:
        src: ../project.tar.gz
        dest: /home/ubuntu/
        mode: '0777'

    - name: "Untar project folder"
      shell: |
        cd /home/ubuntu/
        tar -xzvf project.tar.gz

    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/
        state: absent
        docker_cli: /usr/bin/docker

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/
        docker_cli: /usr/bin/docker
      register: output

    - name: Verify that web and db services are running
      ansible.builtin.assert:
        that:
          - web_container.State == 'running'
          - db_container.State == 'running'
      vars:
        web_container: >-
          {{ output.containers | selectattr("Service", "equalto", "flask_app") | first }}
        db_container: >-
          {{ output.containers | selectattr("Service", "equalto", "db") | first }}
