---
- name: Copy test file to remote EC2
  hosts: ec2
  become: yes
  tasks:
    - name: Copy project to remote server
      copy:
        src: project.tar.gz
        dest: /home/ubuntu/
        mode: '0777'

    - name: "Untar project folder"
      shell: |
        cd /home/ubuntu/
        tar -xzvf project.tar.gz
