# This file is used to create a deployment for the flask app
# The deployment is created with a single replica and the container image is passed as an environment variable

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: "{{ FLASK_IMAGE }}"
          ports:
            - containerPort: 5000
          env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DB_URL
          - name: FLASK_APP
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: FLASK_APP
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: SECRET_KEY
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: API_KEY
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"